; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.3.10 on Sun Feb 20 2022 12:10:06 GMT+0100 (Central European Standard Time)

