; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.3.10 on Tue Mar 01 2022 14:45:35 GMT+0100 (Central European Standard Time)

