; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.3.10 on Sun Feb 20 2022 12:10:06 GMT+0100 (Central European Standard Time)
; Wait for set temperatures to be reached
M116 P0

